{% set name = "napari-layer-table" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-layer-table-{{ version }}.tar.gz
  sha256: cb79a836399e8dfc7a311c131496193a8e0caf7b9e567680ad9da798bb3e5a8c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - napari
    - numpy
    - pandas
    - python >={{ python_min }}
    - qtpy

test:
  imports:
    - napari_layer_table
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mapmanager/napari-layer-table
  summary: A plugin to display a layer as a table.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cudmore
    - goanpeca
    - jaimergp
